version: '3.5'

x-superset-image: &superset-image apache/superset:1.4.0
x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes: &superset-volumes
  - ./data/superset:/app/docker
  - ./data/superset_home:/app/superset_home

services:
  postgres:
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: tagesschau
      POSTGRES_PASSWORD: admin
      PGPORT: 5432
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
      - ./data/postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4:6.8
    restart: unless-stopped
    depends_on:
      - postgres
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@local.de
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 6069:80
    volumes:
       - ./data/pgadmin:/var/lib/pgadmin

  redis:
    image: redis:latest
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

  db:
    env_file: .env.superset
    image: postgres:10
    container_name: superset_db
    restart: unless-stopped
    volumes:
      - ./data/db_home:/var/lib/postgresql/data

  superset:
    env_file: .env.superset
    image: *superset-image
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on: *superset-depends-on
    volumes: *superset-volumes

  superset-init:
    image: *superset-image
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file: .env.superset
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: .env.superset
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes

  superset-worker-beat:
    image: *superset-image
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file: .env.superset
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
