version: '3'

services:
  tagesschau_migrator:
    build: ./migrator/tagesschau
    network_mode: host
    env_file: ../db/.env
    tty: true

  newsapi_migrator:
    build: ./migrator/newsapi
    network_mode: host
    env_file: ../db/.env
    tty: true
