version: '3'

services:
  tagesschau_migrator:
    build: tagesschau
    network_mode: host
    env_file: .env
    tty: true

  newsapi_migrator:
    build: newsapi
    network_mode: host
    env_file: .env
    tty: true
